name: SonarCloud Analysis

on:
  push:

jobs:
  sonarcloud:
    name: Build and analyze
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info -Dsonar.projectKey=A-Muhammad-Azzam-F-2406412152_Modul-2-CI-CD-DevOps -Dsonar.organization=a-muhammad-azzam-f-2406412152 -Dsonar.host.url=https://sonarcloud.io